// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCUum6XskXIJb6ftobrmgP9HX-4kGO_18',
    appId: '1:79921888734:web:cde04e3f296b18059ab14f',
    messagingSenderId: '79921888734',
    projectId: 'urgetalks-90e71',
    authDomain: 'urgetalks-90e71.firebaseapp.com',
    storageBucket: 'urgetalks-90e71.appspot.com',
    measurementId: 'G-1XEF0QTHFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDvqucujCeWwM50oFZFNcF-0T2WlbfpGw',
    appId: '1:79921888734:android:9f6a646d374d9b469ab14f',
    messagingSenderId: '79921888734',
    projectId: 'urgetalks-90e71',
    storageBucket: 'urgetalks-90e71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Zpi3yW0fFDFsfB4qX2wfCgHswOun-3Y',
    appId: '1:79921888734:ios:54ba9f76ad5c1d139ab14f',
    messagingSenderId: '79921888734',
    projectId: 'urgetalks-90e71',
    storageBucket: 'urgetalks-90e71.appspot.com',
    iosBundleId: 'com.urgetalks.urgetalks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Zpi3yW0fFDFsfB4qX2wfCgHswOun-3Y',
    appId: '1:79921888734:ios:c82db2bfba11774d9ab14f',
    messagingSenderId: '79921888734',
    projectId: 'urgetalks-90e71',
    storageBucket: 'urgetalks-90e71.appspot.com',
    iosBundleId: 'com.urgetalks.urge',
  );
}
